const keys = {
  Backquote: {
    rusCaseDown: 'ë',
    rusCaseUp: 'Ё',
    rusCaps: 'Ё',
    rusShiftCaps: 'ë',
    enCaseDown: '`',
    enCaseUp: '~',
    enCaps: '`',
    enShiftCaps: '~',
  },
  Digit1: {
    rusCaseDown: '1',
    rusCaseUp: '!',
    rusCaps: '1',
    rusShiftCaps: '!',
    enCaseDown: '1',
    enCaseUp: '!',
    enCaps: '1',
    enShiftCaps: '!',
  },
  Digit2: {
    rusCaseDown: '2',
    rusCaseUp: '"',
    rusCaps: '2',
    rusShiftCaps: '"',
    enCaseDown: '2',
    enCaseUp: '@',
    enCaps: '2',
    enShiftCaps: '@',
  },
  Digit3: {
    rusCaseDown: '3',
    rusCaseUp: '№',
    rusCaps: '3',
    rusShiftCaps: '№',
    enCaseDown: '3',
    enCaseUp: '#',
    enCaps: '3',
    enShiftCaps: '#',
  },
  Digit4: {
    rusCaseDown: '4',
    rusCaseUp: ';',
    rusCaps: '4',
    rusShiftCaps: ';',
    enCaseDown: '4',
    enCaseUp: '$',
    enCaps: '4',
    enShiftCaps: '$',
  },
  Digit5: {
    rusCaseDown: '5',
    rusCaseUp: '%',
    rusCaps: '5',
    rusShiftCaps: '%',
    enCaseDown: '5',
    enCaseUp: '%',
    enCaps: '5',
    enShiftCaps: '%',
  },
  Digit6: {
    rusCaseDown: '6',
    rusCaseUp: ':',
    rusCaps: '6',
    rusShiftCaps: ':',
    enCaseDown: '6',
    enCaseUp: '^',
    enCaps: '6',
    enShiftCaps: '^',
  },
  Digit7: {
    rusCaseDown: '7',
    rusCaseUp: '?',
    rusCaps: '7',
    rusShiftCaps: '?',
    enCaseDown: '7',
    enCaseUp: '&',
    enCaps: '7',
    enShiftCaps: '&',
  },
  Digit8: {
    rusCaseDown: '8',
    rusCaseUp: '*',
    rusCaps: '8',
    rusShiftCaps: '*',
    enCaseDown: '8',
    enCaseUp: '*',
    enCaps: '8',
    enShiftCaps: '*',
  },
  Digit9: {
    rusCaseDown: '9',
    rusCaseUp: '(',
    rusCaps: '9',
    rusShiftCaps: '(',
    enCaseDown: '9',
    enCaseUp: '(',
    enCaps: '9',
    enShiftCaps: '(',
  },
  Digit0: {
    rusCaseDown: '0',
    rusCaseUp: ')',
    rusCaps: '0',
    rusShiftCaps: ')',
    enCaseDown: '0',
    enCaseUp: ')',
    enCaps: '0',
    enShiftCaps: ')',
  },
  Minus: {
    rusCaseDown: '-',
    rusCaseUp: '_',
    rusCaps: '-',
    rusShiftCaps: '_',
    enCaseDown: '-',
    enCaseUp: '_',
    enCaps: '-',
    enShiftCaps: '_',
  },
  Equal: {
    rusCaseDown: '=',
    rusCaseUp: '+',
    rusCaps: '=',
    rusShiftCaps: '+',
    enCaseDown: '=',
    enCaseUp: '+',
    enCaps: '=',
    enShiftCaps: '+',
  },
  Backspace: {
    rusCaseDown: 'delete',
    rusCaseUp: 'delete',
    rusCaps: 'delete',
    rusShiftCaps: 'delete',
    enCaseDown: 'delete',
    enCaseUp: 'delete',
    enCaps: 'delete',
    enShiftCaps: 'delete',
  },
  Tab: {
    rusCaseDown: 'Tab',
    rusCaseUp: 'Tab',
    rusCaps: 'Tab',
    rusShiftCaps: 'Tab',
    enCaseDown: 'Tab',
    enCaseUp: 'Tab',
    enCaps: 'Tab',
    enShiftCaps: 'Tab',
  },
  KeyQ: {
    rusCaseDown: 'й',
    rusCaseUp: 'Й',
    rusCaps: 'Й',
    rusShiftCaps: 'й',
    enCaseDown: 'q',
    enCaseUp: 'Q',
    enCaps: 'Q',
    enShiftCaps: 'q',
  },
  KeyW: {
    rusCaseDown: 'ц',
    rusCaseUp: 'Ц',
    rusCaps: 'Ц',
    rusShiftCaps: 'ц',
    enCaseDown: 'w',
    enCaseUp: 'W',
    enCaps: 'W',
    enShiftCaps: 'w',
  },
  KeyE: {
    rusCaseDown: 'у',
    rusCaseUp: 'У',
    rusCaps: 'У',
    rusShiftCaps: 'у',
    enCaseDown: 'e',
    enCaseUp: 'E',
    enCaps: 'E',
    enShiftCaps: 'e',
  },
  KeyR: {
    rusCaseDown: 'к',
    rusCaseUp: 'К',
    rusCaps: 'К',
    rusShiftCaps: 'к',
    enCaseDown: 'r',
    enCaseUp: 'R',
    enCaps: 'R',
    enShiftCaps: 'r',
  },
  KeyT: {
    rusCaseDown: 'е',
    rusCaseUp: 'Е',
    rusCaps: 'Е',
    rusShiftCaps: 'е',
    enCaseDown: 't',
    enCaseUp: 'T',
    enCaps: 'T',
    enShiftCaps: 't',
  },
  KeyY: {
    rusCaseDown: 'н',
    rusCaseUp: 'Н',
    rusCaps: 'Н',
    rusShiftCaps: 'н',
    enCaseDown: 'y',
    enCaseUp: 'Y',
    enCaps: 'Y',
    enShiftCaps: 'y',
  },
  KeyU: {
    rusCaseDown: 'г',
    rusCaseUp: 'Г',
    rusCaps: 'Г',
    rusShiftCaps: 'г',
    enCaseDown: 'u',
    enCaseUp: 'U',
    enCaps: 'U',
    enShiftCaps: 'u',
  },
  KeyI: {
    rusCaseDown: 'ш',
    rusCaseUp: 'Ш',
    rusCaps: 'Ш',
    rusShiftCaps: 'ш',
    enCaseDown: 'i',
    enCaseUp: 'I',
    enCaps: 'I',
    enShiftCaps: 'i',
  },
  KeyO: {
    rusCaseDown: 'щ',
    rusCaseUp: 'Щ',
    rusCaps: 'Щ',
    rusShiftCaps: 'щ',
    enCaseDown: 'o',
    enCaseUp: 'O',
    enCaps: 'O',
    enShiftCaps: 'o',
  },
  KeyP: {
    rusCaseDown: 'з',
    rusCaseUp: 'З',
    rusCaps: 'З',
    rusShiftCaps: 'з',
    enCaseDown: 'p',
    enCaseUp: 'P',
    enCaps: 'P',
    enShiftCaps: 'p',
  },
  BracketLeft: {
    rusCaseDown: 'х',
    rusCaseUp: 'Х',
    rusCaps: 'Х',
    rusShiftCaps: 'х',
    enCaseDown: '[',
    enCaseUp: '{',
    enCaps: '[',
    enShiftCaps: '{',
  },
  BracketRight: {
    rusCaseDown: 'ъ',
    rusCaseUp: 'Ъ',
    rusCaps: 'Ъ',
    rusShiftCaps: 'ъ',
    enCaseDown: ']',
    enCaseUp: '}',
    enCaps: ']',
    enShiftCaps: '}',
  },
  Backslash: {
    rusCaseDown: '\\',
    rusCaseUp: '/',
    rusCaps: '\\',
    rusShiftCaps: '/',
    enCaseDown: '\\',
    enCaseUp: '|',
    enCaps: '\\',
    enShiftCaps: '|',
  },
  CapsLock: {
    rusCaseDown: 'CapsLock',
    rusCaseUp: 'CapsLock',
    rusCaps: 'CapsLock',
    rusShiftCaps: 'CapsLock',
    enCaseDown: 'CapsLock',
    enCaseUp: 'CapsLock',
    enCaps: 'CapsLock',
    enShiftCaps: 'CapsLock',
  },
  KeyA: {
    rusCaseDown: 'ф',
    rusCaseUp: 'Ф',
    rusCaps: 'Ф',
    rusShiftCaps: 'ф',
    enCaseDown: 'a',
    enCaseUp: 'A',
    enCaps: 'A',
    enShiftCaps: 'a',
  },
  KeyS: {
    rusCaseDown: 'ы',
    rusCaseUp: 'Ы',
    rusCaps: 'Ы',
    rusShiftCaps: 'ы',
    enCaseDown: 's',
    enCaseUp: 'S',
    enCaps: 'S',
    enShiftCaps: 's',
  },
  KeyD: {
    rusCaseDown: 'в',
    rusCaseUp: 'В',
    rusCaps: 'В',
    rusShiftCaps: 'в',
    enCaseDown: 'd',
    enCaseUp: 'D',
    enCaps: 'D',
    enShiftCaps: 'd',
  },
  KeyF: {
    rusCaseDown: 'а',
    rusCaseUp: 'А',
    rusCaps: 'А',
    rusShiftCaps: 'а',
    enCaseDown: 'f',
    enCaseUp: 'F',
    enCaps: 'F',
    enShiftCaps: 'f',
  },
  KeyG: {
    rusCaseDown: 'п',
    rusCaseUp: 'П',
    rusCaps: 'П',
    rusShiftCaps: 'п',
    enCaseDown: 'g',
    enCaseUp: 'G',
    enCaps: 'G',
    enShiftCaps: 'g',
  },
  KeyH: {
    rusCaseDown: 'р',
    rusCaseUp: 'Р',
    rusCaps: 'Р',
    rusShiftCaps: 'р',
    enCaseDown: 'h',
    enCaseUp: 'H',
    enCaps: 'H',
    enShiftCaps: 'h',
  },
  KeyJ: {
    rusCaseDown: 'о',
    rusCaseUp: 'О',
    rusCaps: 'О',
    rusShiftCaps: 'о',
    enCaseDown: 'j',
    enCaseUp: 'J',
    enCaps: 'J',
    enShiftCaps: 'j',
  },
  KeyK: {
    rusCaseDown: 'л',
    rusCaseUp: 'Л',
    rusCaps: 'Л',
    rusShiftCaps: 'л',
    enCaseDown: 'k',
    enCaseUp: 'K',
    enCaps: 'K',
    enShiftCaps: 'k',
  },
  KeyL: {
    rusCaseDown: 'д',
    rusCaseUp: 'Д',
    rusCaps: 'Д',
    rusShiftCaps: 'д',
    enCaseDown: 'l',
    enCaseUp: 'L',
    enCaps: 'L',
    enShiftCaps: 'l',
  },
  Semicolon: {
    rusCaseDown: 'ж',
    rusCaseUp: 'Ж',
    rusCaps: 'Ж',
    rusShiftCaps: 'ж',
    enCaseDown: ';',
    enCaseUp: ':',
    enCaps: ';',
    enShiftCaps: ':',
  },
  Quote: {
    rusCaseDown: 'э',
    rusCaseUp: 'Э',
    rusCaps: 'Э',
    rusShiftCaps: 'э',
    enCaseDown: "'",
    enCaseUp: '"',
    enCaps: "'",
    enShiftCaps: '"',
  },
  Enter: {
    rusCaseDown: 'Enter',
    rusCaseUp: 'Enter',
    rusCaps: 'Enter',
    rusShiftCaps: 'Enter',
    enCaseDown: 'Enter',
    enCaseUp: 'Enter',
    enCaps: 'Enter',
    enShiftCaps: 'Enter',
  },
  ShiftLeft: {
    rusCaseDown: 'Shift',
    rusCaseUp: 'Shift',
    rusCaps: 'Shift',
    rusShiftCaps: 'Shift',
    enCaseDown: 'Shift',
    enCaseUp: 'Shift',
    enCaps: 'Shift',
    enShiftCaps: 'Shift',
  },
  KeyZ: {
    rusCaseDown: 'я',
    rusCaseUp: 'Я',
    rusCaps: 'Я',
    rusShiftCaps: 'я',
    enCaseDown: 'z',
    enCaseUp: 'Z',
    enCaps: 'Z',
    enShiftCaps: 'z',
  },
  KeyX: {
    rusCaseDown: 'ч',
    rusCaseUp: 'Ч',
    rusCaps: 'Ч',
    rusShiftCaps: 'ч',
    enCaseDown: 'x',
    enCaseUp: 'X',
    enCaps: 'X',
    enShiftCaps: 'x',
  },
  KeyC: {
    rusCaseDown: 'с',
    rusCaseUp: 'С',
    rusCaps: 'С',
    rusShiftCaps: 'с',
    enCaseDown: 'c',
    enCaseUp: 'C',
    enCaps: 'C',
    enShiftCaps: 'c',
  },
  KeyV: {
    rusCaseDown: 'м',
    rusCaseUp: 'М',
    rusCaps: 'М',
    rusShiftCaps: 'м',
    enCaseDown: 'v',
    enCaseUp: 'V',
    enCaps: 'V',
    enShiftCaps: 'v',
  },
  KeyB: {
    rusCaseDown: 'и',
    rusCaseUp: 'И',
    rusCaps: 'И',
    rusShiftCaps: 'и',
    enCaseDown: 'b',
    enCaseUp: 'B',
    enCaps: 'B',
    enShiftCaps: 'b',
  },
  KeyN: {
    rusCaseDown: 'т',
    rusCaseUp: 'Т',
    rusCaps: 'Т',
    rusShiftCaps: 'т',
    enCaseDown: 'n',
    enCaseUp: 'N',
    enCaps: 'N',
    enShiftCaps: 'n',
  },
  KeyM: {
    rusCaseDown: 'ь',
    rusCaseUp: 'Ь',
    rusCaps: 'Ь',
    rusShiftCaps: 'ь',
    enCaseDown: 'm',
    enCaseUp: 'M',
    enCaps: 'M',
    enShiftCaps: 'm',
  },
  Comma: {
    rusCaseDown: 'б',
    rusCaseUp: 'Б',
    rusCaps: 'Б',
    rusShiftCaps: 'б',
    enCaseDown: ',',
    enCaseUp: '<',
    enCaps: ',',
    enShiftCaps: '<',
  },
  Period: {
    rusCaseDown: 'ю',
    rusCaseUp: 'Ю',
    rusCaps: 'Ю',
    rusShiftCaps: 'ю',
    enCaseDown: '.',
    enCaseUp: '>',
    enCaps: '.',
    enShiftCaps: '>',
  },
  Slash: {
    rusCaseDown: '.',
    rusCaseUp: ',',
    rusCaps: '.',
    rusShiftCaps: ',',
    enCaseDown: '/',
    enCaseUp: '?',
    enCaps: '/',
    enShiftCaps: '?',
  },
  ArrowUp: {
    rusCaseDown: '▲',
    rusCaseUp: '▲',
    rusCaps: '▲',
    rusShiftCaps: '▲',
    enCaseDown: '▲',
    enCaseUp: '▲',
    enCaps: '▲',
    enShiftCaps: '▲',
  },
  ShiftRight: {
    rusCaseDown: 'Shift',
    rusCaseUp: 'Shift',
    rusCaps: 'Shift',
    rusShiftCaps: 'Shift',
    enCaseDown: 'Shift',
    enCaseUp: 'Shift',
    enCaps: 'Shift',
    enShiftCaps: 'Shift',
  },
  Fn: {
    rusCaseDown: 'fn',
    rusCaseUp: 'fn',
    rusCaps: 'fn',
    rusShiftCaps: 'fn',
    enCaseDown: 'fn',
    enCaseUp: 'fn',
    enCaps: 'fn',
    enShiftCaps: 'fn',
  },
  ControlLeft: {
    rusCaseDown: 'control',
    rusCaseUp: 'control',
    rusCaps: 'control',
    rusShiftCaps: 'control',
    enCaseDown: 'control',
    enCaseUp: 'control',
    enCaps: 'control',
    enShiftCaps: 'control',
  },
  AltLeft: {
    rusCaseDown: 'alt',
    rusCaseUp: 'alt',
    rusCaps: 'alt',
    rusShiftCaps: 'alt',
    enCaseDown: 'alt',
    enCaseUp: 'alt',
    enCaps: 'alt',
    enShiftCaps: 'alt',
  },
  MetaLeft: {
    rusCaseDown: 'command',
    rusCaseUp: 'command',
    rusCaps: 'command',
    rusShiftCaps: 'command',
    enCaseDown: 'command',
    enCaseUp: 'command',
    enCaps: 'command',
    enShiftCaps: 'command',
  },
  Space: {
    rusCaseDown: '',
    rusCaseUp: ' ',
    rusCaps: ' ',
    rusShiftCaps: ' ',
    enCaseDown: ' ',
    enCaseUp: ' ',
    enCaps: ' ',
    enShiftCaps: ' ',
  },
  MetaRight: {
    rusCaseDown: 'command',
    rusCaseUp: 'command',
    rusCaps: 'command',
    rusShiftCaps: 'command',
    enCaseDown: 'command',
    enCaseUp: 'command',
    enCaps: 'command',
    enShiftCaps: 'command',
  },
  ArrowLeft: {
    rusCaseDown: '◄',
    rusCaseUp: '◄',
    rusCaps: '◄',
    rusShiftCaps: '◄',
    enCaseDown: '◄',
    enCaseUp: '◄',
    enCaps: '◄',
    enShiftCaps: '◄',
  },
  ArrowDown: {
    rusCaseDown: '▼',
    rusCaseUp: '▼',
    rusCaps: '▼',
    rusShiftCaps: '▼',
    enCaseDown: '▼',
    enCaseUp: '▼',
    enCaps: '▼',
    enShiftCaps: '▼',
  },
  ArrowRight: {
    rusCaseDown: '►',
    rusCaseUp: '►',
    rusCaps: '►',
    rusShiftCaps: '►',
    enCaseDown: '►',
    enCaseUp: '►',
    enCaps: '►',
    enShiftCaps: '►',
  },
  AltRight: {
    rusCaseDown: 'alt',
    rusCaseUp: 'alt',
    rusCaps: 'alt',
    rusShiftCaps: 'alt',
    enCaseDown: 'alt',
    enCaseUp: 'alt',
    enCaps: 'alt',
    enShiftCaps: 'alt',
  },
};

export default keys;
